<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Tue Jan 21 15:36:01 CST 2014.

define('DOMJUDGE_VERSION', '3.4.0');

define('BINDIR',      '/opt/domjudge/domserver/bin');
define('ETCDIR',      '/opt/domjudge/domserver/etc');
define('WWWDIR',      '/opt/domjudge/domserver/www');
define('LIBDIR',      '/opt/domjudge/domserver/lib');
define('LIBEXTDIR',   '/opt/domjudge/domserver/lib/ext');
define('LIBWWWDIR',   '/opt/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/opt/domjudge/domserver/lib/submit');
define('LOGDIR',      '/opt/domjudge/domserver/log');
define('RUNDIR',      '/opt/domjudge/domserver/run');
define('TMPDIR',      '/opt/domjudge/domserver/tmp');
define('SUBMITDIR',   '/opt/domjudge/domserver/submissions');

define('SUBMIT_DEFAULT', 2);
define('ENABLE_CMDSUBMIT_SERVER', 0);
define('ENABLE_WEBSUBMIT_SERVER', 1);

set_include_path(get_include_path() . PATH_SEPARATOR . LIBEXTDIR);
